//! Apple Vision OCR on a synthetic dialog with ground-truth label positions
//! (`tests/fixtures/ocr`, regenerated by `generate_dialog.swift`).
//!
//! Needs no GUI session or permissions, so it runs in CI on macOS.

#![cfg(target_os = "macos")]

use std::fs::File;
use std::path::PathBuf;

use argus_perception::{OcrBackend, OcrRegion, VisionOcr};
use argus_protocol::{Bounds, Frame, FrameId, PixelBuffer, Timestamp};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Label {
    text: String,
    x: f32,
    y: f32,
    width: f32,
    height: f32,
}

fn fixtures() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/ocr")
}

/// The dialog as a 2x frame of the point region (0, 0, 480, 240).
fn dialog_frame() -> Frame {
    let decoder = png::Decoder::new(std::io::BufReader::new(
        File::open(fixtures().join("dialog.png")).unwrap(),
    ));
    let mut reader = decoder.read_info().unwrap();
    let mut data = vec![0; reader.output_buffer_size().unwrap()];
    let info = reader.next_frame(&mut data).unwrap();
    assert_eq!(info.color_type, png::ColorType::Rgba);
    data.truncate(info.buffer_size());
    let pixels = PixelBuffer::new(info.width, info.height, data).unwrap();
    let bounds = Bounds::new(0.0, 0.0, 480.0, 240.0).unwrap();
    Frame::new(FrameId(1), Timestamp(0), bounds, 2.0, pixels).unwrap()
}

fn comparable(text: &str) -> String {
    text.chars().filter(|c| !c.is_whitespace()).flat_map(char::to_lowercase).collect()
}

fn center_inside(region: &OcrRegion, label: &Label) -> bool {
    let (cx, cy) =
        (region.rect.x + region.rect.width / 2.0, region.rect.y + region.rect.height / 2.0);
    (label.x..=label.x + label.width).contains(&cx)
        && (label.y..=label.y + label.height).contains(&cy)
}

#[test]
fn recognizes_every_label_at_its_position() {
    let labels: Vec<Label> =
        serde_json::from_reader(File::open(fixtures().join("dialog.json")).unwrap()).unwrap();
    let regions = VisionOcr::new().detect(&dialog_frame()).unwrap();

    for label in &labels {
        let found =
            regions.iter().find(|region| comparable(&region.text) == comparable(&label.text));
        let Some(region) = found else {
            panic!("`{}` not recognized; got {regions:#?}", label.text);
        };
        assert!(
            center_inside(region, label),
            "`{}` at wrong position: {region:?} vs {label:?}",
            label.text
        );
        assert!(region.confidence.get() > 0.0, "`{}` has zero confidence", label.text);
    }
    assert_eq!(regions.len(), labels.len(), "unexpected extra text: {regions:#?}");
}
