//! Evaluates the heuristic detector on real AppKit controls rendered at 2x in
//! light and dark appearance (`tests/fixtures/vision`, regenerated by
//! `generate_controls.swift`). Pure Rust: runs on any OS.
//!
//! Prints per-fixture metrics; asserts minimum quality so regressions fail.

// The printed report is the point of these tests (`--nocapture`).
#![allow(clippy::print_stdout)]

use std::fs::File;
use std::path::PathBuf;

use argus_perception::{HeuristicDetector, VisualCandidate, VisualPerceptionBackend};
use argus_protocol::{Bounds, CheckState, Frame, FrameId, PixelBuffer, Role, Timestamp};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct Truth {
    role: String,
    name: String,
    checked: Option<bool>,
    x: f32,
    y: f32,
    width: f32,
    height: f32,
}

fn fixtures() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/fixtures/vision")
}

fn load(name: &str) -> Frame {
    let file = File::open(fixtures().join(name)).unwrap();
    let mut reader = png::Decoder::new(std::io::BufReader::new(file)).read_info().unwrap();
    let mut data = vec![0; reader.output_buffer_size().unwrap()];
    let info = reader.next_frame(&mut data).unwrap();
    data.truncate(info.buffer_size());
    let pixels = PixelBuffer::new(info.width, info.height, data).unwrap();
    let bounds = Bounds::new(0.0, 0.0, info.width as f32 / 2.0, info.height as f32 / 2.0).unwrap();
    Frame::new(FrameId(1), Timestamp(0), bounds, 2.0, pixels).unwrap()
}

fn iou(d: &VisualCandidate, t: &Truth) -> f32 {
    let left = d.rect.x.max(t.x);
    let top = d.rect.y.max(t.y);
    let right = (d.rect.x + d.rect.width).min(t.x + t.width);
    let bottom = (d.rect.y + d.rect.height).min(t.y + t.height);
    let overlap = (right - left).max(0.0) * (bottom - top).max(0.0);
    overlap / (d.rect.width * d.rect.height + t.width * t.height - overlap)
}

fn role_name(role: Role) -> String {
    serde_json::to_value(role).unwrap().as_str().unwrap().to_owned()
}

struct Metrics {
    found: usize,
    correct_role: usize,
    states: usize,
    correct_states: usize,
    truths: usize,
    detections: usize,
}

fn evaluate(image: &str) -> Metrics {
    let truths: Vec<Truth> =
        serde_json::from_reader(File::open(fixtures().join("controls.json")).unwrap()).unwrap();
    let detections = HeuristicDetector::default().detect(&load(image)).unwrap();

    let mut used = vec![false; detections.len()];
    let (mut found, mut correct_role, mut states, mut correct_states) = (0, 0, 0, 0);
    println!("--- {image}: {} detections", detections.len());
    for truth in &truths {
        let best = detections
            .iter()
            .enumerate()
            .filter(|(i, _)| !used[*i])
            .map(|(i, d)| (i, iou(d, truth)))
            .max_by(|a, b| a.1.total_cmp(&b.1))
            .filter(|(_, overlap)| *overlap >= 0.4);
        match best {
            Some((i, overlap)) => {
                used[i] = true;
                found += 1;
                let role = role_name(detections[i].role);
                let ok = role == truth.role;
                correct_role += usize::from(ok);
                if let Some(expected) = truth.checked {
                    states += 1;
                    let expected =
                        if expected { CheckState::Checked } else { CheckState::Unchecked };
                    correct_states += usize::from(detections[i].state.checked == Some(expected));
                }
                println!(
                    "  {} {:12} {:24} -> {:12} iou={overlap:.2} state={:?}",
                    if ok { "✓" } else { "~" },
                    truth.role,
                    truth.name,
                    role,
                    detections[i].state.checked
                );
            }
            None => println!("  ✗ {:12} {:24} missed", truth.role, truth.name),
        }
    }
    for (i, d) in detections.iter().enumerate().filter(|(i, _)| !used[*i]) {
        println!("  + unmatched #{i} {:12} {:?}", role_name(d.role), d.rect);
    }
    Metrics {
        found,
        correct_role,
        states,
        correct_states,
        truths: truths.len(),
        detections: detections.len(),
    }
}

fn report(image: &str) -> Metrics {
    let m = evaluate(image);
    println!(
        "  recall {}/{} = {:.2}, role accuracy {}/{} = {:.2}, precision {}/{} = {:.2}",
        m.found,
        m.truths,
        m.found as f32 / m.truths as f32,
        m.correct_role,
        m.found,
        m.correct_role as f32 / m.found.max(1) as f32,
        m.found,
        m.detections,
        m.found as f32 / m.detections.max(1) as f32
    );
    m
}

/// Minimum quality on the fixtures. Current results are higher; the margin
/// lets heuristics evolve while catching real regressions.
fn assert_quality(m: &Metrics) {
    let ratio = |a: usize, b: usize| a as f32 / b.max(1) as f32;
    assert!(ratio(m.found, m.truths) >= 0.85, "localization recall regressed");
    assert!(ratio(m.correct_role, m.found) >= 0.85, "role accuracy regressed");
    assert!(ratio(m.found, m.detections) >= 0.85, "precision regressed");
    assert_eq!(m.correct_states, m.states, "check states must be read correctly");
}

#[test]
fn light_appearance() {
    assert_quality(&report("controls_light.png"));
}

#[test]
fn dark_appearance() {
    assert_quality(&report("controls_dark.png"));
}
